//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaPresentacion.Idioma.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca De.
        /// </summary>
        internal static string Acerca_De {
            get {
                return ResourceManager.GetString("Acerca De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar:.
        /// </summary>
        internal static string btnAgregar {
            get {
                return ResourceManager.GetString("btnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BackUp.
        /// </summary>
        internal static string btnBackup {
            get {
                return ResourceManager.GetString("btnBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string btnBuscarS {
            get {
                return ResourceManager.GetString("btnBuscarS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria.
        /// </summary>
        internal static string btnCategoria {
            get {
                return ResourceManager.GetString("btnCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Venta:.
        /// </summary>
        internal static string btnCrearVenta {
            get {
                return ResourceManager.GetString("btnCrearVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Pdf.
        /// </summary>
        internal static string btnDescargarPdf {
            get {
                return ResourceManager.GetString("btnDescargarPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btnEliminar {
            get {
                return ResourceManager.GetString("btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Excel.
        /// </summary>
        internal static string btnExcel {
            get {
                return ResourceManager.GetString("btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar/Editar.
        /// </summary>
        internal static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string btnIngresar {
            get {
                return ResourceManager.GetString("btnIngresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string btnLimpiarForm {
            get {
                return ResourceManager.GetString("btnLimpiarForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negocio.
        /// </summary>
        internal static string btnNegocio {
            get {
                return ResourceManager.GetString("btnNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        internal static string btnProductos {
            get {
                return ResourceManager.GetString("btnProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string btnRegistrar {
            get {
                return ResourceManager.GetString("btnRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registar Compra.
        /// </summary>
        internal static string btnRegistrarCompra {
            get {
                return ResourceManager.GetString("btnRegistrarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Venta.
        /// </summary>
        internal static string btnRegistrarVenta {
            get {
                return ResourceManager.GetString("btnRegistrarVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        internal static string btnSeleccionarIdioma {
            get {
                return ResourceManager.GetString("btnSeleccionarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Detalle Compra.
        /// </summary>
        internal static string btnVerDetalle {
            get {
                return ResourceManager.GetString("btnVerDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Detalle.
        /// </summary>
        internal static string btnVerDetalleVenta {
            get {
                return ResourceManager.GetString("btnVerDetalleVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compras.
        /// </summary>
        internal static string Compras {
            get {
                return ResourceManager.GetString("Compras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Venta.
        /// </summary>
        internal static string gbInfo {
            get {
                return ResourceManager.GetString("gbInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Cliente.
        /// </summary>
        internal static string gbInfoCliente {
            get {
                return ResourceManager.GetString("gbInfoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Compra.
        /// </summary>
        internal static string gbInfoCompra {
            get {
                return ResourceManager.GetString("gbInfoCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Producto:.
        /// </summary>
        internal static string gbInfoProducto {
            get {
                return ResourceManager.GetString("gbInfoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Proveedor.
        /// </summary>
        internal static string gbInfoProveedor {
            get {
                return ResourceManager.GetString("gbInfoProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Compra.
        /// </summary>
        internal static string gboInfoCompra {
            get {
                return ResourceManager.GetString("gboInfoCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por:.
        /// </summary>
        internal static string lblBuscar {
            get {
                return ResourceManager.GetString("lblBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio:.
        /// </summary>
        internal static string lblCambio {
            get {
                return ResourceManager.GetString("lblCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad:.
        /// </summary>
        internal static string lblCantidad {
            get {
                return ResourceManager.GetString("lblCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria.
        /// </summary>
        internal static string lblCategoria {
            get {
                return ResourceManager.GetString("lblCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string lblClientes {
            get {
                return ResourceManager.GetString("lblClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        internal static string lblCodigo {
            get {
                return ResourceManager.GetString("lblCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cód. Producto:.
        /// </summary>
        internal static string lblCodProducto {
            get {
                return ResourceManager.GetString("lblCodProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña:.
        /// </summary>
        internal static string lblConfContraseña {
            get {
                return ResourceManager.GetString("lblConfContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lblContraseña {
            get {
                return ResourceManager.GetString("lblContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CUIT:.
        /// </summary>
        internal static string lblCuit {
            get {
                return ResourceManager.GetString("lblCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string lblDescripcion {
            get {
                return ResourceManager.GetString("lblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        internal static string lblDetalle2 {
            get {
                return ResourceManager.GetString("lblDetalle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de compras.
        /// </summary>
        internal static string lblDetalleCompra {
            get {
                return ResourceManager.GetString("lblDetalleCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Venta.
        /// </summary>
        internal static string lblDetalleVenta {
            get {
                return ResourceManager.GetString("lblDetalleVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección:.
        /// </summary>
        internal static string lblDireccion {
            get {
                return ResourceManager.GetString("lblDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Documento.
        /// </summary>
        internal static string lblDoc {
            get {
                return ResourceManager.GetString("lblDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email:.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado:.
        /// </summary>
        internal static string lblEstado {
            get {
                return ResourceManager.GetString("lblEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        internal static string lblFecha {
            get {
                return ResourceManager.GetString("lblFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Fin.
        /// </summary>
        internal static string lblFechaFin {
            get {
                return ResourceManager.GetString("lblFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        internal static string lblFechaInicio {
            get {
                return ResourceManager.GetString("lblFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma:.
        /// </summary>
        internal static string lblIdioma {
            get {
                return ResourceManager.GetString("lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista Categorias:.
        /// </summary>
        internal static string lblListaCategorias {
            get {
                return ResourceManager.GetString("lblListaCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista Clientes:.
        /// </summary>
        internal static string lblListaClientes {
            get {
                return ResourceManager.GetString("lblListaClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Productos:.
        /// </summary>
        internal static string lblListaProducto {
            get {
                return ResourceManager.GetString("lblListaProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista Proveedores.
        /// </summary>
        internal static string lblListaProveedores {
            get {
                return ResourceManager.GetString("lblListaProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo.
        /// </summary>
        internal static string lblLogo {
            get {
                return ResourceManager.GetString("lblLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Cambio.
        /// </summary>
        internal static string lblMontoCambio {
            get {
                return ResourceManager.GetString("lblMontoCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Pago.
        /// </summary>
        internal static string lblMontoPago {
            get {
                return ResourceManager.GetString("lblMontoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MontoTotal.
        /// </summary>
        internal static string lblMontoTotal {
            get {
                return ResourceManager.GetString("lblMontoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo:.
        /// </summary>
        internal static string lblNombreCliente {
            get {
                return ResourceManager.GetString("lblNombreCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Negocio.
        /// </summary>
        internal static string lblNombreNegocio {
            get {
                return ResourceManager.GetString("lblNombreNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario:.
        /// </summary>
        internal static string lblNombreUsuario {
            get {
                return ResourceManager.GetString("lblNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número Documento:.
        /// </summary>
        internal static string lblNroDoc {
            get {
                return ResourceManager.GetString("lblNroDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paga Con:.
        /// </summary>
        internal static string lblPagaCon {
            get {
                return ResourceManager.GetString("lblPagaCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string lblPrecio {
            get {
                return ResourceManager.GetString("lblPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Compra:.
        /// </summary>
        internal static string lblPrecioCompra {
            get {
                return ResourceManager.GetString("lblPrecioCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Venta:.
        /// </summary>
        internal static string lblPrecioVenta {
            get {
                return ResourceManager.GetString("lblPrecioVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto:.
        /// </summary>
        internal static string lblProducto {
            get {
                return ResourceManager.GetString("lblProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        internal static string lblProductos {
            get {
                return ResourceManager.GetString("lblProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        internal static string lblProveedor {
            get {
                return ResourceManager.GetString("lblProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razon Social.
        /// </summary>
        internal static string lblRazonSocial {
            get {
                return ResourceManager.GetString("lblRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Venta.
        /// </summary>
        internal static string lblRegistrar {
            get {
                return ResourceManager.GetString("lblRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Venta.
        /// </summary>
        internal static string lblRegistrarVenta {
            get {
                return ResourceManager.GetString("lblRegistrarVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de compras.
        /// </summary>
        internal static string lblReporteCompra {
            get {
                return ResourceManager.GetString("lblReporteCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol:.
        /// </summary>
        internal static string lblRol {
            get {
                return ResourceManager.GetString("lblRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock:.
        /// </summary>
        internal static string lblStock {
            get {
                return ResourceManager.GetString("lblStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        internal static string lblTelefono {
            get {
                return ResourceManager.GetString("lblTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso Sistema.
        /// </summary>
        internal static string lbltitulo {
            get {
                return ResourceManager.GetString("lbltitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de Ventas..
        /// </summary>
        internal static string lbltitulo2 {
            get {
                return ResourceManager.GetString("lbltitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista Usuario:.
        /// </summary>
        internal static string lblTituloUsuario {
            get {
                return ResourceManager.GetString("lblTituloUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total a Pagar:.
        /// </summary>
        internal static string lblTotalPagar {
            get {
                return ResourceManager.GetString("lblTotalPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string lblUsuarios {
            get {
                return ResourceManager.GetString("lblUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenedor.
        /// </summary>
        internal static string Mantenedor {
            get {
                return ResourceManager.GetString("Mantenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores.
        /// </summary>
        internal static string Proveedores {
            get {
                return ResourceManager.GetString("Proveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        internal static string Reportes {
            get {
                return ResourceManager.GetString("Reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte Compras.
        /// </summary>
        internal static string SubMenuReporteCompras {
            get {
                return ResourceManager.GetString("SubMenuReporteCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte Ventas.
        /// </summary>
        internal static string SubMenuReporteVentas {
            get {
                return ResourceManager.GetString("SubMenuReporteVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string txtNUsuario {
            get {
                return ResourceManager.GetString("txtNUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        internal static string Ventas {
            get {
                return ResourceManager.GetString("Ventas", resourceCulture);
            }
        }
    }
}
